ERROR SQL 

System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Appv2.Program.Main(String[] args) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 49
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:-1,State:0,Class:20



ERROR INTERNO 

System.ServiceModel.EndpointNotFoundException, TIPO: System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at https://test.salesforce.com/services/Soap/c/43.0/0DFm00000008PV5 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. ---> System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Appv2.sForce.Soap.login(loginRequest request)
   at Appv2.sForce.SoapClient.Appv2.sForce.Soap.login(loginRequest request) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190460
   at Appv2.sForce.SoapClient.login(LoginScopeHeader LoginScopeHeader, String username, String password) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190468
   at Appv2.Program.Login() in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 254
   at Appv2.Program.Main(String[] args) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 40System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()



ERROR INTERNO 

System.ServiceModel.EndpointNotFoundException, TIPO: System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at https://test.salesforce.com/services/Soap/c/43.0/0DFm00000008PV5 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. ---> System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Appv2.sForce.Soap.login(loginRequest request)
   at Appv2.sForce.SoapClient.Appv2.sForce.Soap.login(loginRequest request) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190460
   at Appv2.sForce.SoapClient.login(LoginScopeHeader LoginScopeHeader, String username, String password) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190468
   at Appv2.Program.Login() in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 254
   at Appv2.Program.Main(String[] args) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 40System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()



ERROR INTERNO 

System.ServiceModel.EndpointNotFoundException, TIPO: System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at https://test.salesforce.com/services/Soap/c/43.0/0DFm00000008PV5 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. ---> System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Appv2.sForce.Soap.login(loginRequest request)
   at Appv2.sForce.SoapClient.Appv2.sForce.Soap.login(loginRequest request) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190460
   at Appv2.sForce.SoapClient.login(LoginScopeHeader LoginScopeHeader, String username, String password) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190468
   at Appv2.Program.Login() in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 256
   at Appv2.Program.Main(String[] args) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 40System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()



ERROR DESDE RESPUESTA SOAP SALESFORCE 

System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at https://test.salesforce.com/services/Soap/c/43.0/0DFm00000008PV5 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. ---> System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   at System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Appv2.sForce.Soap.login(loginRequest request)
   at Appv2.sForce.SoapClient.Appv2.sForce.Soap.login(loginRequest request) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190460
   at Appv2.sForce.SoapClient.login(LoginScopeHeader LoginScopeHeader, String username, String password) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Connected Services\sForce\Reference.cs:line 190468
   at Appv2.Program.Login() in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 261
   at Appv2.Program.Main(String[] args) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 40System.Net.WebException: The remote name could not be resolved: 'test.salesforce.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()



ERROR INTERNO 

System.InvalidOperationException, TIPO: System.InvalidOperationException: The connection was not closed. The connection's current state is open.
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Appv2.Program.terminar(String tabla, String idx, String nuevo, String estado, String desc) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 234
   at Appv2.Program.crearCuenta(String id, String n, String s, String r) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 460
   at Appv2.Program.Main(String[] args) in D:\pend\Proyectos\Torque\Integración Salesforce\Integracion\Demonio\v2\Appv2\Appv2\Program.cs:line 78



